<?php
/**
 * NeoTheme Austrlia (Neo Industries Pty Ltd)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Neo Industries Pty LTD Non-Distributable Software Modification License (NDSML)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.neotheme.com.au/legal/licenses/NDSM.html
 * If the license is not included with the package or for any other reason, 
 * you did not receive your licence please send an email to 
 * license@neotheme.com.au so we can send you a copy immediately.
 *
 * This software comes with no warrenty of any kind. By Using this software, the user agrees to hold 
 * Neo Industries Pty Ltd harmless of any damage it may cause.
 *
 * @category    modules
 * @module      NeoTheme_ImageRotator
 * @copyright   Copyright (c) 2011 Neo Industries Pty Ltd (http://www.neotheme.com.au)
 * @license     http://www.neotheme.com.au/  Non-Distributable Software Modification License(NDSML 1.0)
 */
/**
 * @see NeoTheme_Blog_Block_Post_Summary
 */
 $formatType = Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_FORMAT_TYPE);
 $format = ($formatType != 'custom')?
    Mage::app()->getLocale()->getDateTimeFormat($formatType): 
    Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_CUSTOM_FORMAT);
?>


<h2><?php echo $this->getPost()->getTitle(); ?></h2>
<div class="blog-entry-meta clearfix">
    <span class="pull-right blog-comment-count">

        <?php if ( Mage::helper('neotheme_blog')->isDefaultCommentingEnabled()) : ?>
        <?php 
         $commentCount = $this->getPost()->getComments()->count();
         $commentText =  ($commentCount == 1) ? $this->__("comment"):$this->__("comments");
        ?>
        <?php echo $commentCount; ?> <?php echo $commentText;?>
 
        <?php endif; ?>

    </span>
    <span class="pull-left">

        by 
        
        <?php if ($authorName = $this->getPost()->getAuthor()) :?>
            <span><?php echo $this->__('by'); ?> <?php echo $authorName; ?></span> 
        <?php endif;?>

        on 

        <span>
            <?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>
            <?php  echo Mage::app()->getLocale()->date($date)->toString($format); ?>
            <?php // $timestamp = (int) Mage::app()->getLocale()->date($date)->getTimestamp() ;?>
            <?php // echo date('d D', $timestamp)?><?php // echo date('M', $timestamp)?>
        </span>
    </span>
</div> <!-- .blog-entry-meta -->
<div class="clearfix">
    <div class="blog-entry-image">
       <?php echo $this->getPost()->getSummary(); ?>

    </div>
    <div class="blog-entry-text">
      <div class="blog-entry-text-in">
        <?php echo $this->getPost()->getContent(); ?>

        <br>
        <?php if ($this->getPost()->getCategories()->count() > 0):?>
        <ul class="post-categories">
            <?php echo $this->__('Posted In: ');?>
            <?php $i = 0; ?>
            <?php foreach($this->getPost()->getCategories() as $category):?>
                <?php $catName =  ($i > 0)? ',' . $category->getName() : $category->getName(); ?>
                    <li><a href="<?php echo $category->getListUrl();?>"><?php echo $catName; ?></a></li>
                <?php $i++; ?>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>


        <div class="clearfix blog-entry-buttons">
          <span class="pull-left"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>" class="btn btn-success green-gradient-2"><?php echo $this->__($this->getPost()->getReadMoreText()); ?></a></span>
          <span class="pull-right">
            <ul class="list-unstyled blog-social-links">
              <li>Share article</li>
              <li><a href="#" class="social-twitter"></a></li>
              <li><a href="#" class="social-facebook"></a></li>
              <li><a href="#" class="social-google"></a></li>
            </ul>
          </span>
        </div> <!-- .clearfix -->
      </div>
    </div> <!-- .blog-entry-text -->
</div> <!-- .clearfix -->





