<div id="product-slider">
      <div class="container">
        <div id="the-product-slider" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="item active">
              <div class="clearfix">
                <div class="product-slider-text">
                  <p>New Fireworks for 2013</p>
                  <h2>
                    New Fireworks
                    <br />for 2013
                  </h2>
                  <div class="hidden-xs"><a href="#" class="btn btn-success">Shop Now</a></div>
                </div> <!-- .product-slider-text -->
                <div class="product-slider-image">
                  <img src="images/clipart/slider-product.png" alt="" class="img-responsive" />
                </div> <!-- .product-slider-image -->
              </div> <!-- .clearfix -->
            </div>
            <div class="item">
              <div class="clearfix">
                <div class="product-slider-text">
                  <p>New Fireworks for 2014</p>
                  <h2>
                    New Fireworks
                    <br />for 2014
                  </h2>
                  <div class="hidden-xs"><a href="#" class="btn btn-success">Shop Now</a></div>
                </div> <!-- .product-slider-text -->
                <div class="product-slider-image">
                  <img src="images/clipart/slider-product.png" alt="" class="img-responsive" />
                </div> <!-- .product-slider-image -->
              </div> <!-- .clearfix -->
            </div>
          </div>
        </div>
        <a class="slider-nav left" href="#the-product-slider" data-slide="prev"></a>
        <a class="slider-nav right" href="#the-product-slider" data-slide="next"></a>
      </div> <!-- .container -->
    </div> <!-- #product-slider -->